"""added industry and website to company

Revision ID: 4bac7a11f1d7
Revises: d369ac4c59c3
Create Date: 2025-08-19 01:02:57.821186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bac7a11f1d7'
down_revision: Union[str, Sequence[str], None] = 'd369ac4c59c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###