"""Updating (may not be any changes), using for production

Revision ID: 8d46548b9c09
Revises: 4bac7a11f1d7
Create Date: 2025-08-22 01:59:03.727049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d46548b9c09'
down_revision: Union[str, Sequence[str], None] = '4bac7a11f1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###